accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("dashboard", views.dashboard, name="dashboard")
]

btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pages.urls')),
    path("enquiries/", include("enquiries.urls")),
    path("listings/", include('listings.urls')),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name = "listings"

urlpatterns = [
    path("", views.ListingPageListView.as_view(), name="listings_index"),
    path("<int:pk>/", views.ListingPageDetailView.as_view(), name="listing_detail"),
    path("search/", views.search, name="search"),
]

templates/partials/_alert_message.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{message.tags}} alert-dismissible fade show " role="alert">
                <div class="text-center">
                    <strong>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            Error:
                        {% else %}
                            {{message.tags|title}}:
                        {% endif %}
                    </strong> {{message}}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
        Copyright &copy;
        <span class="year"></span> BT Real Estate
    </footer>

templates/partials/_navbar.html
    {% load staticfiles %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'img/logo.png' %}" class="logo" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li 
                {% if "/" == request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %} 
              >
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li 
                {% if 'about' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %}   
              >
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li 
                {% if 'listings' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %} 
              >
                <a class="nav-link" href="{% url 'listings:listings_index' %}">Featured Listings</a>
              </li>
            </ul>
    
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <span class="navbar-text">
                  Welcome {{user.username}}
              </span>
              <li 
                {% if 'dashboard' in request.path %}
                    class="nav-item active mr-3 ml-2"
                {% else %}
                    class="nav-item mr-3 ml-2"
                {% endif %} 
              >
              <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                <i class="fas fa-sign-in-alt"></i>
                My Dashboard</a>
              </li>
              <li 
                {% if 'logout' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %} 
              >
              <a class="nav-link" href="javascript:{document.getElementById('logoutform').submit()}">
                <i class="fas fa-sign-out-alt"></i>
                Logout</a>
                <form id="logoutform" method="POST" action="{% url 'accounts:logout' %}">
                  {% csrf_token %}
                  <input type="hidden" name="">
                </form>
              </li>
              {% else %}
                <li 
                {% if 'register' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    class="nav-item mr-3"
                {% endif %} 
                >
                <a class="nav-link" href="{% url 'accounts:signup' %}">
                  <i class="fas fa-user-plus"></i> Signup</a>
                </li>
                <li 
                  {% if 'login' in request.path %}
                      class="nav-item active mr-3"
                  {% else %}
                      class="nav-item mr-3"
                  {% endif %} 
                >
                <a class="nav-link" href="{% url 'accounts:login' %}">
                  <i class="fas fa-sign-in-alt"></i>
                  Login</a>
                </li>
              {% endif %}
              
            </ul>
          </div>
        </div>
    </nav>

templates/partials/_topbar.html
    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <i class="fas fa-phone"></i> (617)-555-5555
            </div>
            <div class="col-md-4">
              <i class="fas fa-envelope-open"></i> contact@btrealestate.co
            </div>
            <div class="col-md-4">
              <div class="social text-right">
                <a target="_blank" href="https://www.twitter.com">
                  <i class="fab fa-twitter"></i>
                </a>
                <a target="_blank" href="https://www.facebook.com">
                  <i class="fab fa-facebook"></i>
                </a>
                <a target="_blank" href="https://www.linkedin.com">
                  <i class="fab fa-linkedin"></i>
                </a>
                <a target="_blank" href="https://www.instagram.com">
                  <i class="fab fa-instagram"></i>
                </a>
                <a target="_blank" href="https://www.pinterest.com">
                  <i class="fab fa-pinterest"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
    </section>