btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pages.urls')),
    path("enquiries/", include("enquiries.urls")),
    path("listings/", include('listings.urls')),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enquiries/urls.py
from django.urls import path
from . import views

app_name = "enquiries"
urlpatterns = [
    path("enquiry/", views.enquiry, name="enquiry")
]

listings/urls.py
from django.urls import path
from . import views

app_name = "listings"

urlpatterns = [
    path("", views.ListingPageListView.as_view(), name="listings_index"),
    path("<int:pk>/", views.ListingPageDetailView.as_view(), name="listing_detail"),
    path("search/", views.search, name="search"),
]

listings/models.py
from django.db import models
from realtors.models import Realtor
from datetime import datetime
# Create your models here.

class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    zipcode = models.CharField(max_length=10)
    description = models.TextField()
    price = models.PositiveIntegerField()
    bedrooms = models.PositiveIntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    squarefeet = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    is_published = models.BooleanField(default=True)
    published_date = models.DateTimeField(default=datetime.now)
    photo_main = models.ImageField(upload_to="photos/%Y/%m/%d")
    photo_1 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)
    photo_2 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)
    photo_3 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)
    photo_4 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)
    photo_5 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)
    photo_6 = models.ImageField(upload_to="photos/%Y/%m/%d", blank=True)

    def __str__(self):
        return self.title

listings/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from listings.choices import state_choices, bedroom_choices, price_choices
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Listing
# Create your views here.
class ListingPageListView(ListView):
    queryset = Listing.objects.order_by('-published_date').filter(is_published=True)
    template_name = "listings/listings.html"
    context_object_name = "listings"
    paginate_by = 6


class ListingPageDetailView(DetailView):
    model = Listing
    context_object_name = "listing"
    template_name = "listings/listing.html"

# class ListingSearchTemplateView(TemplateView):
#     template_name = "listings/search.html"

def search(request):
    listings = Listing.objects.order_by("-published_date").filter(is_published=True)

    #Keywords
    if 'keywords' in request.GET:
        keywords = request.GET.get('keywords')
        if keywords:
            listings = listings.filter(description__icontains=keywords)
    
    #City
    if 'city' in request.GET:
        city = request.GET.get('city')
        if city:
            listings = listings.filter(city__iexact=city)

    #State
    if 'state' in request.GET:
        state = request.GET.get('state')
        if state:
            listings = listings.filter(state__iexact=state)

    #Bedrooms
    if 'bedrooms' in request.GET:
        bedrooms = request.GET.get('bedrooms')
        if bedrooms:
            listings = listings.filter(bedrooms__iexact =bedrooms)

    #Price
    if 'price' in request.GET:
        price = request.GET.get('price')
        if price:
            listings = listings.filter(price__lte=price)
    
    page = request.GET.get('page',1)
    paginator = Paginator(listings, 6)
    
    try:
        listings = paginator.page(page)
    except PageNotAnInteger:
        listings = paginator.page(1)
    except EmptyPage:
        listings = paginator.page(paginator.num_pages)

    context = {
        'price_choices':price_choices,
        'bedroom_choices': bedroom_choices,
        'state_choices': state_choices,
        'listings': listings,
        'values': request.GET
    }
    return render(request, "listings/search.html", context)

templates/listings/listing.html
{% extends 'base.html' %}
{% block body_block %}
{% load humanize %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{listing.title}}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
        </div>
      </div>
    </div>
  </section>
    
      <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings_index' %}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{listing.title}}</li>
        </ol>
      </nav>
    </div>
  </section>
      {% include 'partials/_alert_message.html' %}
      <!-- Listing -->
      <section id="listing" class="py-4">
        <div class="container">
          <a href="{% url 'listings:listings_index' %}" class="btn btn-light mb-4">Back To Listings</a>
          <div class="row">
            <div class="col-md-9">
              <!-- Home Main Image -->
              <img src="{{listing.photo_main.url}}" alt="" class="img-main img-fluid mb-3">
              <!-- Thumbnails -->
              <div class="row mb-5 thumbs">
                <div class="col-md-2">
                  <a href="{{listing.photo_1.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_1.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                <div class="col-md-2">
                  <a href="{{listing.photo_2.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_2.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                <div class="col-md-2">
                  <a href="{{listing.photo_3.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_3.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                <div class="col-md-2">
                  <a href="{{listing.photo_4.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_4.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                <div class="col-md-2">
                  <a href="{{listing.photo_5.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_5.url}}" alt="" class="img-fluid">
                  </a>
                </div>
                <div class="col-md-2">
                  <a href="{{listing.photo_6.url}}" data-lightbox="home-images">
                    <img src="{{listing.photo_6.url}}" alt="" class="img-fluid">
                  </a>
                </div>
              </div>
              <!-- Fields -->
              <div class="row mb-5 fields">
                <div class="col-md-6">
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-money-bill-alt"></i> Asking Price:
                      <span class="float-right">${{listing.price|intcomma}}</span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-bed"></i> Bedrooms:
                      <span class="float-right">{{listing.bedrooms}}</span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-bath"></i> Bathrooms:
                      <span class="float-right">{{listing.bathrooms}}</span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-car"></i> Garage:
                      <span class="float-right">{{listing.garage}}
                      </span>
                    </li>
                  </ul>
                </div>
                <div class="col-md-6">
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-th-large"></i> Square Feet:
                      <span class="float-right">{{listing.squarefeet}}</span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-square"></i> Lot Size:
                      <span class="float-right">{{listing.lot_size}}
                      </span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-calendar"></i> Listing Date:
                      <span class="float-right">{{listing.published_date|timesince}}</span>
                    </li>
                    <li class="list-group-item text-secondary">
                      <i class="fas fa-bed"></i> Realtor:
                      <span class="float-right">{{listing.realtor}}
                      </span>
                    </li>
    
    
                  </ul>
                </div>
              </div>
    
              <!-- Description -->
              <div class="row mb-5">
                <div class="col-md-12">
                  {{listing.description}}
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card mb-3">
                <img class="card-img-top" src="{{listing.realtor.photo.url}}" alt="Realtor Photo">
                <div class="card-body">
                  <h5 class="card-title">Property Realtor</h5>
                  <h6 class="text-secondary">{{listing.realtor.name}}</h6>
                </div>
              </div>
              <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
            </div>
          </div>
        </div>
      </section>
    
      <!-- Inquiry Modal -->
      <div class="modal fade" id="inquiryModal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
              <button type="button" class="close" data-dismiss="modal">
                <span>&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form action="{% url 'enquiries:enquiry' %}" method="POST">
                {% csrf_token %}
                {% if user.is_authenticated %}
                  <input type="hidden" name="user_id" value="{{user.pk}}">
                {% else %}
                  <input type="hidden" name="user_id" value="0">
                {% endif %}
                  <input type="hidden" name="realtor_email" value={{listing.realtor.email}}>
                  <input type="hidden" name="listing_id" value={{listing.pk}}>
                <div class="form-group">
                  <label for="property_name" class="col-form-label">Property:</label>
                  <input type="text" name="listing" class="form-control" value="{{listing.title}}" >
                </div>
                <div class="form-group">
                  <label for="name" class="col-form-label">Name:</label>
                  <input type="text" name="name" class="form-control" 
                    {% if user.is_authenticated %}
                      value="{{user.first_name}} {{user.last_name}}"
                    {% endif %}
                  required>
                </div>
                <div class="form-group">
                  <label for="email" class="col-form-label">Email:</label>
                  <input type="email" name="email" class="form-control"
                    {% if user.is_authenticated %}
                      value="{{user.email}}"
                    {% endif %}
                  required>
                </div>
                <div class="form-group">
                  <label for="phone" class="col-form-label">Phone:</label>
                  <input type="text" name="phone" class="form-control">
                </div>
                <div class="form-group">
                  <label for="message" class="col-form-label">Message:</label>
                  <textarea name="message" class="form-control"></textarea>
                </div>
                <hr>
                <input type="submit" value="Send" class="btn btn-block btn-secondary">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock body_block %}

templates/listings/listings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load humanize %}
<section id="showcase-inner" class="py-5 text-white">
        <div class="container">
          <div class="row text-center">
            <div class="col-md-12">
              <h1 class="display-4">Browse Our Properties</h1>
              <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
            </div>
          </div>
        </div>
      </section>
    
      <!-- Breadcrumb -->
      <section id="bc" class="mt-3">
        <div class="container">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'index' %}">
                  <i class="fas fa-home"></i> Home</a>
              </li>
              <li class="breadcrumb-item active"> Browse Listings</li>
            </ol>
          </nav>
        </div>
      </section>
    
      <!-- Listings -->
      <section id="listings" class="py-4">
        <div class="container">
          <div class="row">
              {% if listings %}
                {% for listing in listings %}
                    <!-- Listing  -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card listing-preview">
                        <img class="card-img-top" src="{{listing.photo_main.url}}" alt="House Image">
                        <div class="card-img-overlay">
                            <h2>
                            <span class="badge badge-secondary text-white">$ {{listing.price|intcomma}}</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                            <h4 class="text-primary">{{listing.title}}</h4>
                            <p>
                                <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-th-large"></i> Sqft: {{listing.squarefeet}}</div>
                            <div class="col-6">
                                <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                            <div class="col-6">
                                <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-user"></i> {{listing.realtor}}</div>
                            </div>
                            <div class="row text-secondary pb-2">
                            <div class="col-6">
                                <i class="fas fa-clock"></i> {{ listing.published_date|timesince }}</div>
                            </div>
                            <hr>
                            <a href="{% url 'listings:listing_detail' listing.pk %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                        </div>
                    </div>
                {% endfor %}
              {% else %}
                <div class="row text-center">
                    <div class="col-md-12">
                        <h1 class="display-4">OOPS ! No properties listed. Please Check Back Later</h1>
                    </div>
                </div>
              {% endif %}
            
          </div>
  
          <div class="row">
            <div class="col-md-12">
              {% if is_paginated %}
                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center pagination-lg">
                    {% if page_obj.has_previous %}
                      <li class="page-item">
                        <a class="page-link" style="background-color:rgb(41,171,136); color:white;" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                        </a>
                      </li>
                    {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                      </li> 
                    {% endif %}
                    {% for current_page in paginator.page_range %}
                      {% if page_obj.number ==  current_page %}
                        <li class="page-item active">
                          <a class="page-link">{{current_page}}<span class="sr-only">(current)</span></a>
                        </li>
                      {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{current_page}}">{{current_page}} <span class="sr-only">(current)</span></a></li>
                      {% endif %}
                    {% endfor %}
      
                    {% if page_obj.has_next %}
                      <li class="page-item">
                        <a class="page-link" style="background-color:rgb(41,171,136); color:white;" href="?page={{page_obj.next_page_number}}" aria-label="Previous">
                          <span aria-hidden="true">&raquo;</span>
                          <span class="sr-only">Previous</span>
                        </a>
                      </li>
                    {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                          <span class="sr-only">Next</span>
                      </li> 
                    {% endif %}

                  </ul>
                </nav>
              {% endif %}
            </div>
          </div>
        </div>
      </section>
{% endblock body_block %}

templates/listings/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block body_block %}
<section id="showcase-inner" class="showcase-search text-white py-5">
        <div class="container">
          <div class="row text-center">
            <div class="col-md-12">
              <form action="{% url 'listings:search' %}">
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Keywords</label>
                    <input type="text" name="keywords" value="{{values.keywords}}" class="form-control" placeholder="Keyword (Pool, Garage, etc)">
                  </div>
    
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">City</label>
                    <input type="text" name="city" value="{{values.city}}" class="form-control" placeholder="City">
                  </div>
    
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">State</label>
                    <select name="state" class="form-control">
                      <option selected="true" disabled="disabled">State (All)</option>
                      {% for key,value in state_choices.items %}
                        <option value="{{key}}"
                            {% if key == values.state %}
                                selected
                            {% endif %}
                        >{{value}}</option>
                      {% endfor %}                      
                    </select>
                  </div>
                </div>
                <!-- Form Row 2 -->
                <div class="form-row">
                  <div class="col-md-6 mb-3">
                    <label class="sr-only">Bedrooms</label>
                    <select name="bedrooms" class="form-control">
                      <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                      {% for key,value in bedroom_choices.items %}
                        <option value="{{key}}"
                        {% if key == values.bedrooms %}
                            selected
                        {% endif %}
                        >{{value}}</option>
                      {% endfor %} 
                      </select>
                  </div>
                  <div class="col-md-6 mb-3">
                    <select name="price" class="form-control">
                      <option selected="true" disabled="disabled">Max Price (All)</option>
                      <option value="100000">$100,000</option>
                      {% for key,value in price_choices.items %}
                        <option value="{{key}}"
                        {% if key == values.price %}
                            selected
                        {% endif %}
                        >{{value}}</option>
                      {% endfor %} 
                      </select>
                  </div>
                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
              </form>
            </div>
          </div>
        </div>
      </section>
    
      <!-- Breadcrumb -->
      <section id="bc" class="mt-3">
        <div class="container">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'index' %}">
                  <i class="fas fa-home"></i> Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="{% url 'listings:listings_index' %}">Browse Listings</a>
              </li>
              <li class="breadcrumb-item active"> Search Results</li>
            </ol>
          </nav>
        </div>
      </section>
    
      <!-- Listings -->
      <section id="listings" class="py-4">
            <div class="container">
              <div class="row">
                  {% if listings %}
                    {% for listing in listings %}
                        <!-- Listing  -->
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card listing-preview">
                            <img class="card-img-top" src="{{listing.photo_main.url}}" alt="House Image">
                            <div class="card-img-overlay">
                                <h2>
                                <span class="badge badge-secondary text-white">$ {{listing.price|intcomma}}</span>
                                </h2>
                            </div>
                            <div class="card-body">
                                <div class="listing-heading text-center">
                                <h4 class="text-primary">{{listing.title}}</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                                </div>
                                <hr>
                                <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-th-large"></i> Sqft: {{listing.squarefeet}}</div>
                                <div class="col-6">
                                    <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                                </div>
                                <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                                <div class="col-6">
                                    <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
                                </div>
                                <hr>
                                <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-user"></i> {{listing.realtor}}</div>
                                </div>
                                <div class="row text-secondary pb-2">
                                <div class="col-6">
                                    <i class="fas fa-clock"></i> {{ listing.published_date|timesince }}</div>
                                </div>
                                <hr>
                                <a href="{% url 'listings:listing_detail' listing.pk %}" class="btn btn-primary btn-block">More Info</a>
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                  {% else %}
                    <div class="row text-center">
                        <div class="col-md-12">
                            <h1 class="display-4">Oops! There is no available listing under the given filter. Please Check Back Later</h1>
                        </div>
                    </div>
                  {% endif %}
                
              </div>
      
              <div class="row">
                <div class="col-md-12">
                  {% if listings.has_other_pages %}
                    <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-center pagination-lg">
                        {% if listings.has_previous %}
                          <li class="page-item">
                            <a class="page-link" style="background-color:rgb(41,171,136); color:white;" href="?page={{listings.previous_page_number}}" aria-label="Previous">
                              <span aria-hidden="true">&laquo;</span>
                              <span class="sr-only">Previous</span>
                            </a>
                          </li>
                        {% else %}
                          <li class="page-item disabled">
                              <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                          </li> 
                        {% endif %}
                        {% for current_page in listings.paginator.page_range %}
                          {% if listings.number ==  current_page %}
                            <li class="page-item active">
                              <a class="page-link">{{current_page}}<span class="sr-only">(current)</span></a>
                            </li>
                          {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{current_page}}">{{current_page}} <span class="sr-only">(current)</span></a></li>
                          {% endif %}
                        {% endfor %}
          
                        {% if listings.has_next %}
                          <li class="page-item">
                            <a class="page-link" style="background-color:rgb(41,171,136); color:white;" href="?page={{listings.next_page_number}}" aria-label="Previous">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">Previous</span>
                            </a>
                          </li>
                        {% else %}
                          <li class="page-item disabled">
                              <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                              <span class="sr-only">Next</span>
                          </li> 
                        {% endif %}
    
                      </ul>
                    </nav>
                  {% endif %}
                </div>
              </div>
            </div>
          </section>
{% endblock body_block %}
<h1>Search</h1>